In [40]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [6]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [7]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [8]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [9]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [10]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename (columns={'purchase_amount_(usd)':'purchase_amount'})

In [11]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [12]:
#create a age group columnn
labels = ['Young_Adult','Adult','Middle_aged','senior']
df['age_group'] = pd.qcut(df['age'],q=4,labels=labels)

In [13]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle_aged
1   19  Young_Adult
2   50  Middle_aged
3   21  Young_Adult
4   45  Middle_aged
5   46  Middle_aged
6   63       senior
7   27  Young_Adult
8   26  Young_Adult
9   57  Middle_aged

In [14]:
df['frequency_of_purchases'].head(10)

0    Fortnightly
1    Fortnightly
2         Weekly
3         Weekly
4       Annually
5         Weekly
6      Quarterly
7         Weekly
8       Annually
9      Quarterly
Name: frequency_of_purchases, dtype: object

In [15]:
frequency_mapping = {
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}
df['purchases_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [16]:
df[['purchases_frequency_days','frequency_of_purchases']].head(10)

   purchases_frequency_days frequency_of_purchases
0                        14            Fortnightly
1                        14            Fortnightly
2                         7                 Weekly
3                         7                 Weekly
4                       365               Annually
5                         7                 Weekly
6                        90              Quarterly
7                         7                 Weekly
8                       365               Annually
9                        90              Quarterly

In [17]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchases_frequency_days'],
      dtype='object')

In [18]:
df[['discount_applied','promo_code_used']].head(11)

   discount_applied promo_code_used
0               Yes             Yes
1               Yes             Yes
2               Yes             Yes
3               Yes             Yes
4               Yes             Yes
5               Yes             Yes
6               Yes             Yes
7               Yes             Yes
8               Yes             Yes
9               Yes             Yes
10              Yes             Yes

In [19]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [ ]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "root"
password = quote_plus("563736367@Tu")
host = "localhost"
port = "3306"
database = "CUSTOMER_BEHAVIOUR"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

df.to_sql("customer_behaviour", engine, if_exists="replace", index=False)

print("Data loaded successfully")